/// <reference types="cypress"/>

import reg from "../Pages/Register.cy"

const regs = new reg()

describe("Verifying a Registration Page",()=>{
    beforeEach("Open the login page",()=>{
       regs.visit()
    })
    it("Verify successfully registration with valid data",()=>{
        regs.FirstName().type("John")
        regs.LastName().type("Kayode")
        regs.Email().type("Johnkayode23@gmail.com")
        regs.BusinessName().type("Trybe")
        regs.Country().type("Nigeria")
        regs.dropdown().click()
        regs.dropdown().should('contain','Nigeria')
        regs.PhoneNumber().type('09087657622')
        regs.Password().type('Windows123@')
        regs.ConfrimPassword().type('Windows123@')
        regs.StarterB_radioButton().click()
        regs.FalseRadioButton().click()
        regs.CheckBox1().click()
        regs.CheckBox2().click()
        regs.SignupButton().click()
        cy.wait(3000)
        regs.notification().should('have.text','User account was created successfully')

    })
    it("Verify registration with mis-matched password",()=>{
        regs.FirstName().type("John")
        regs.LastName().type("Kayode")
        regs.Email().type("kayodeJohn@gmail.com")
        regs.BusinessName().type("Trybe")
        regs.Country().type("Nigeria")
        regs.dropdown().click()
        regs.dropdown().should('contain','Nigeria')
        regs.PhoneNumber().type('7061332298')
        regs.Password().type('Windows123@')
        regs.ConfrimPassword().type('Windows@123')
        regs.StarterB_radioButton().click()
        regs.FalseRadioButton().click()
        regs.CheckBox1().click()
        regs.CheckBox2().click()
        regs.SignupButton().click()
        regs.errormessage().should('contain.text','Password does not match')
     
    })
    it("verify registration with existing email",()=>{
        regs.FirstName().type("Olatunde")
        regs.LastName().type("Muiz")
        regs.Email().type("Johnkayode23@gmail.com")
        regs.BusinessName().type("Creative Gallery")
        regs.Country().type("Nigeria")
        regs.dropdown().click()
        regs.dropdown().should('contain','Nigeria')
        regs.PhoneNumber().type('7061332798')
        regs.Password().type('Windows123@')
        regs.ConfrimPassword().type('Windows123@')
        regs.StarterB_radioButton().click()
        regs.FalseRadioButton().click()
        regs.CheckBox1().click()
        regs.CheckBox2().click()
        regs.SignupButton().click()
        cy.wait(3000)
        regs.notification2().should('have.text','This email address is already taken')
    })

    it("verifying registration with invalid email format",()=>{
        regs.FirstName().type("Olatunde")
        regs.LastName().type("Muiz")
        regs.Email().type("Muiz.olatunde12@gmaicom")
        regs.BusinessName().type("Creative Gallery")
        regs.Country().type("Nigeria")
        regs.dropdown().click()
        regs.dropdown().should('contain','Nigeria')
        regs.PhoneNumber().type('7061332798')
        regs.Password().type('Windows123@')
        regs.ConfrimPassword().type('Windows123@')
        regs.StarterB_radioButton().click()
        regs.FalseRadioButton().click()
        regs.CheckBox1().click()
        regs.CheckBox2().click()
        regs.SignupButton().click()
        regs.errormessage().should('contain.text',"'email' is not a valid email")

    })
    it("verify registration with missing fiedls",()=>{
        regs.FirstName().type("Olatunde")
        regs.Email().type("Muiz.olatunde12@gmail.com")
        regs.Country().type("Nigeria")
        regs.dropdown().click()
        regs.dropdown().should('contain','Nigeria')
        regs.PhoneNumber().type('7061332798')
        regs.Password().type('Windows123@')
        regs.ConfrimPassword().type('Windows123@')
        regs.FalseRadioButton().click()
        regs.CheckBox1().click()
        regs.CheckBox2().click()
        regs.SignupButton().click()
        regs.errormessage().should('contain.text','Business name is Required')
        regs.errormessage().should('contain.text','Last name is Required')
        regs.errormessage().should('contain.text','Select business type')
    })

    it("verify registration without clicking terms and condition",()=>{

        regs.FirstName().type("Olatunde")
        regs.LastName().type("Muiz")
        regs.Email().type("Muiz.olatu@gmail.com")
        regs.BusinessName().type("Creative Gallery")
        regs.Country().type("Nigeria")
        regs.dropdown().click()
        regs.dropdown().should('contain','Nigeria')
        regs.PhoneNumber().type('7061212798')
        regs.Password().type('Windows123@')
        regs.ConfrimPassword().type('Windows123@')
        regs.StarterB_radioButton().click()
        regs.FalseRadioButton().click()
        regs.CheckBox1().click()
        regs.SignupButton().should('be.disabled')

    })

    it("verify registration with password lesser than 8 characters",()=>{
        regs.FirstName().type("Olatunde")
        regs.LastName().type("Muiz")
        regs.Email().type("Muiz.232@gmail.com")
        regs.BusinessName().type("Creative Gallery")
        regs.Country().type("Nigeria")
        regs.dropdown().click()
        regs.dropdown().should('contain','Nigeria')
        regs.PhoneNumber().type('7061212798')
        regs.Password().type('W@1')
        regs.ConfrimPassword().type('W@1')
        regs.StarterB_radioButton().click()
        regs.FalseRadioButton().click()
        regs.CheckBox1().click()
        regs.CheckBox2().click()
        regs.SignupButton().click()
        regs.errormessage().should('have.text','Password must contain min of 8 characters with at least 1 lowercase, 1 uppercase, 1 numeric and 1 special characters')
    })
    it("verify registration with special character added to phone number field",()=>{
        regs.FirstName().type("Olatunde")
        regs.LastName().type("Muiz")
        regs.Email().type("Muiz.43522@gmail.com")
        regs.BusinessName().type("Creative Gallery")
        regs.Country().type("Nigeria")
        regs.dropdown().click()
        regs.dropdown().should('contain','Nigeria')
        regs.PhoneNumber().type('.70612127967')
        regs.Password().type('Windows123@')
        regs.ConfrimPassword().type('Windows123@')
        regs.StarterB_radioButton().click()
        regs.FalseRadioButton().click()
        regs.CheckBox1().click()
        regs.CheckBox2().click()
        regs.SignupButton().click()
        regs.notification2().should('have.text','Invalid Data')
    })
    it("verify registration with existing phone number",()=>{
        regs.FirstName().type("Olatunde")
        regs.LastName().type("Muiz")
        regs.Email().type("Muiz.ola2@gmail.com")
        regs.BusinessName().type("Creative Gallery")
        regs.Country().type("Nigeria")
        regs.dropdown().click()
        regs.dropdown().should('contain','Nigeria')
        regs.PhoneNumber().type('09087657622')
        regs.Password().type('Windows123@')
        regs.ConfrimPassword().type('Windows123@')
        regs.StarterB_radioButton().click()
        regs.FalseRadioButton().click()
        regs.CheckBox1().click()
        regs.CheckBox2().click()
        regs.SignupButton().click()
        cy.wait(2000)
        regs.notification2().should('have.text','This phone number is already taken')
    })
})